### ISSUE TITLE
The plugin blocks certain information

### ISSUE THREAD

**Issue by ghost** [GoldpawsStuff/ChatCleaner#2]
Hello, I am a big fan of your plugin. I am using your full set of plugins.

When I was using this plugin, I found a problem, that is, it will block some information. For example, the dialogue of NPC. When doing missions, sometimes there is no voice in the NPC's dialogue, and the dialogue bubble disappears very quickly, which makes it impossible for me to see the dialogue clearly.

I am a person who enjoys doing tasks. I like to understand the plot through tasks. So, are there some options to set whether to block certain information?

**Comment by goldpaw** [comment]
Yes and no. The ability to manually disable separate filters is a feature I've planned, just never gotten around to finishing. The structure is in place, though. 

In theory, you could use the following in-game command followed by a `/reload` to disable the creature- and boss message filter: 
```Lua
/run ChatCleaner_DB.DisableFilterCreatures = true
``` 
I have NOT tested this, though. Just looked at my code and imaging this should do it. 

I do plan to add a simple graphical gui to toggle the filters, though, so I'll leave this issue open until that is done.

**Comment by Dcryfm** [comment]
Thank you, I will wait for the update.

**Comment by Goldpaw** [comment]
I imagine I forgot to close this issue, as this was fixed/changed a long time ago.
