### ISSUE TITLE
The channel name is not hidden

### ISSUE THREAD

**Issue by zhenduow** [GoldpawsStuff/ChatCleaner#4]
Hi,

Thank you for this addon. Since Wrath Classic, I have found that the names of my chat channels such as "2.LookingForGroup" or "1.Trade - City" are not hidden any more by this addon. They were working fine back in BC Classic.

Prior to this issue, my chat messages are in this format:
[1]Player1: WTB Nobles Deck
Now they are:
[1. Trade - City][Player1]: WTB Nobles Deck

I have two other chat addons: ChatAlphaZero and ChatCopyPaste. However, even if I disable them, this problem is still there. How can I hide the channel names as in the past?

Thank you very much!

**Comment by Goldpaw** [comment]
should work better now
