### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by ghost** [GoldpawsStuff/ChatCleaner#5]
Hello, I was attempting to try this addon but it doesn't seem to work.

It appears in my addons list, but not in my addons options.
I am not getting any errors from bugsack, so not sure what is going on?

Thanks :)

**Comment by nz13s** [comment]
Same here, not changing anything unfortunately. With Glass not being worked on, this seems like the next best option, hope it gets resolved

**Comment by JBabbb** [comment]
I am in the EXACT same boat as you!
Although Glass does have a fan update that is working, I want to give this a try considering it has the original authors support.

I've tried everything... I've disabled all addons, deleted chat-cache, deleted WTF files of other possible conflicting chat addons, but it just gives me nothing, like the addon isn't even existing. :(

**Comment by Rezy942** [comment]
"BasicChatMods" addon does everything this one tries to do, and completely fails.
Not sure why author isnt responding either. Just delete it and move on.
